/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package traviator42.gui.merchant;

import traviator42.gui.common.MainWindow;
import traviator42.gui.common.Traviator42;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Ror
 */
public class Merch2VillyReciever extends javax.swing.JDialog {
    boolean tradeRoutes;
    /**
     * Creates new form villageName
     */
    public Merch2VillyReciever(java.awt.Frame parent, boolean modal, boolean tradeRoutes) {
        super(parent, MainWindow.messages[159][MainWindow.language], modal);
        initComponents();
        this.tradeRoutes = tradeRoutes;
        label.setText(MainWindow.messages[177][MainWindow.language]);
        jButton1.setText(MainWindow.messages[71][MainWindow.language]);
        jButton2.setText(MainWindow.messages[106][MainWindow.language]);
 //<editor-fold defaultstate="collapsed" desc=" Центр экрана ">
 //делаем чтобы приложение появилось в центре экрана
 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
 Dimension frameSize = getSize();
 setLocation(new Point((screenSize.width - frameSize.width) / 2,
 (screenSize.height - frameSize.height) / 2));
///////////////////////////////////////////////////
 //</editor-fold>
        comboboxTo.removeAllItems();
        for(int i = 0; i<MainWindow.vilList.size(); i++)
            comboboxTo.addItem(MainWindow.vilList.get(i).name);
        comboboxTo.removeItem(MainWindow.futureRow[0]);
        checkBoxUseCoordinates.setEnabled(!tradeRoutes);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton(MainWindow.natiPic[4][14]);
        jButton2 = new javax.swing.JButton(MainWindow.natiPic[4][24]);
        label = new javax.swing.JLabel();
        textFieldX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        checkBoxUseCoordinates = new javax.swing.JCheckBox();
        textFieldY = new javax.swing.JTextField();
        comboboxTo = new javax.swing.JComboBox();
        to = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label.setText("Где тренировать солдат?");

        textFieldX.setEnabled(false);

        jLabel2.setText("Y");

        jLabel1.setText("X");

        checkBoxUseCoordinates.setText(MainWindow.messages[15][MainWindow.language]);
        checkBoxUseCoordinates.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxUseCoordinatesItemStateChanged(evt);
            }
        });

        textFieldY.setEnabled(false);

        comboboxTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxToActionPerformed(evt);
            }
        });

        to.setText(MainWindow.messages[14][MainWindow.language]);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboboxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(to)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxUseCoordinates)
                                .addGap(128, 128, 128))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldY))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxUseCoordinates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to)
                    .addComponent(textFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(textFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(checkBoxUseCoordinates.isSelected() == false){
            MainWindow.futureRow[1] = comboboxTo.getSelectedItem().toString();
            MainWindow.futureRow[9] = "";
        }else{
            MainWindow.futureRow[1] = "";
            MainWindow.futureRow[9] = textFieldX.getText() + "/" + textFieldY.getText();
        }
        Merch3ResoCount mrc = new Merch3ResoCount(Traviator42.mainWindow, true, tradeRoutes);
        mrc.setVisible(true);
        
        
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void checkBoxUseCoordinatesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxUseCoordinatesItemStateChanged
        if (checkBoxUseCoordinates.isSelected()) {
            comboboxTo.setEnabled(false);
            textFieldX.setEnabled(true);
            textFieldY.setEnabled(true);
        } else {
            comboboxTo.setEnabled(true);
            textFieldX.setEnabled(false);
            textFieldY.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxUseCoordinatesItemStateChanged

    private void comboboxToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxToActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox checkBoxUseCoordinates;
    public static javax.swing.JComboBox comboboxTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField textFieldX;
    private javax.swing.JTextField textFieldY;
    public static javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
