/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package traviator42.gui.architector;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.openqa.selenium.By;
import traviator42.gui.common.MainWindow;
import traviator42.gui.common.Traviator42;

/**
 *
 * @author Ror
 */
public class Architector3Reso extends javax.swing.JDialog {
static int resoName;
    /**
     * Creates new form villageName
     */
    public Architector3Reso(java.awt.Frame parent, boolean modal) {
        super(parent, MainWindow.messages[184][MainWindow.language], modal);
        initComponents();
        jButton2.setText(MainWindow.messages[106][MainWindow.language]);
        buttonResoRefresh.setText(MainWindow.messages[228][MainWindow.language]);
 //<editor-fold defaultstate="collapsed" desc=" Центр экрана ">
 //делаем чтобы приложение появилось в центре экрана
 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
 Dimension frameSize = getSize();
 setLocation(new Point((screenSize.width - frameSize.width) / 2,
 (screenSize.height - frameSize.height) / 2));
///////////////////////////////////////////////////
 //</editor-fold>
       labelNames();
       resoRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton(MainWindow.natiPic[4][25]);
        jPanel7 = new javax.swing.JPanel();
        id1 = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();
        id3 = new javax.swing.JLabel();
        id4 = new javax.swing.JLabel();
        id5 = new javax.swing.JLabel();
        id6 = new javax.swing.JLabel();
        id7 = new javax.swing.JLabel();
        id8 = new javax.swing.JLabel();
        id9 = new javax.swing.JLabel();
        id10 = new javax.swing.JLabel();
        id11 = new javax.swing.JLabel();
        id12 = new javax.swing.JLabel();
        id13 = new javax.swing.JLabel();
        id14 = new javax.swing.JLabel();
        id15 = new javax.swing.JLabel();
        id16 = new javax.swing.JLabel();
        id17 = new javax.swing.JLabel();
        id18 = new javax.swing.JLabel();
        buttonAllPlusOne = new javax.swing.JButton(MainWindow.natiPic[4][13]);
        buttonResoRefresh = new javax.swing.JButton(MainWindow.natiPic[4][21]);
        labelReso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id1.setText("jLabel1");
        id1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id1MouseClicked(evt);
            }
        });
        jPanel7.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 44, 42));

        id2.setText("jLabel1");
        id2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id2MouseClicked(evt);
            }
        });
        jPanel7.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 44, 42));

        id3.setText("jLabel1");
        id3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id3MouseClicked(evt);
            }
        });
        jPanel7.add(id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 44, 42));

        id4.setText("jLabel1");
        id4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id4MouseClicked(evt);
            }
        });
        jPanel7.add(id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 44, 42));

        id5.setText("jLabel1");
        id5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id5MouseClicked(evt);
            }
        });
        jPanel7.add(id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 44, 42));

        id6.setText("jLabel1");
        id6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id6MouseClicked(evt);
            }
        });
        jPanel7.add(id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 44, 42));

        id7.setText("jLabel1");
        id7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id7MouseClicked(evt);
            }
        });
        jPanel7.add(id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 44, 42));

        id8.setText("jLabel1");
        id8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id8MouseClicked(evt);
            }
        });
        jPanel7.add(id8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 44, 42));

        id9.setText("jLabel1");
        id9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id9MouseClicked(evt);
            }
        });
        jPanel7.add(id9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 44, 42));

        id10.setText("jLabel1");
        id10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id10MouseClicked(evt);
            }
        });
        jPanel7.add(id10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 44, 42));

        id11.setText("jLabel1");
        id11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id11MouseClicked(evt);
            }
        });
        jPanel7.add(id11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 44, 42));

        id12.setText("jLabel1");
        id12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id12MouseClicked(evt);
            }
        });
        jPanel7.add(id12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 44, 42));

        id13.setText("jLabel1");
        id13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id13MouseClicked(evt);
            }
        });
        jPanel7.add(id13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 44, 42));

        id14.setText("jLabel1");
        id14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id14MouseClicked(evt);
            }
        });
        jPanel7.add(id14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 44, 42));

        id15.setText("jLabel1");
        id15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id15MouseClicked(evt);
            }
        });
        jPanel7.add(id15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 44, 42));

        id16.setText("jLabel1");
        id16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id16MouseClicked(evt);
            }
        });
        jPanel7.add(id16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 44, 42));

        id17.setText("jLabel1");
        id17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id17MouseClicked(evt);
            }
        });
        jPanel7.add(id17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 44, 42));

        id18.setText("jLabel1");
        id18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id18MouseClicked(evt);
            }
        });
        jPanel7.add(id18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 44, 42));

        buttonAllPlusOne.setText("All +1");
        buttonAllPlusOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllPlusOneActionPerformed(evt);
            }
        });
        jPanel7.add(buttonAllPlusOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        buttonResoRefresh.setText("jButton1");
        buttonResoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResoRefreshActionPerformed(evt);
            }
        });
        jPanel7.add(buttonResoRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelReso.setText("jLabel1");
        jPanel7.add(labelReso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void id1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id1MouseClicked
        reso(id1);
    }//GEN-LAST:event_id1MouseClicked

    private void id2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id2MouseClicked
        reso(id2);
    }//GEN-LAST:event_id2MouseClicked

    private void id3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id3MouseClicked
       reso(id3);
    }//GEN-LAST:event_id3MouseClicked

    private void id4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id4MouseClicked
        reso(id4);
    }//GEN-LAST:event_id4MouseClicked

    private void id5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id5MouseClicked
        reso(id5);
    }//GEN-LAST:event_id5MouseClicked

    private void id6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id6MouseClicked
        reso(id6);
    }//GEN-LAST:event_id6MouseClicked

    private void id7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id7MouseClicked
        reso(id7);
    }//GEN-LAST:event_id7MouseClicked

    private void id8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id8MouseClicked
        reso(id8);
    }//GEN-LAST:event_id8MouseClicked

    private void id9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id9MouseClicked
       reso(id9);
    }//GEN-LAST:event_id9MouseClicked

    private void id10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id10MouseClicked
        reso(id10);
    }//GEN-LAST:event_id10MouseClicked

    private void id11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id11MouseClicked
        reso(id11);
    }//GEN-LAST:event_id11MouseClicked

    private void id12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id12MouseClicked
        reso(id12);
    }//GEN-LAST:event_id12MouseClicked

    private void id13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id13MouseClicked
       reso(id13);
    }//GEN-LAST:event_id13MouseClicked

    private void id14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id14MouseClicked
        reso(id14);
    }//GEN-LAST:event_id14MouseClicked

    private void id15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id15MouseClicked
        reso(id15);
    }//GEN-LAST:event_id15MouseClicked

    private void id16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id16MouseClicked
        reso(id16);
    }//GEN-LAST:event_id16MouseClicked

    private void id17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id17MouseClicked
        reso(id17);
    }//GEN-LAST:event_id17MouseClicked

    private void id18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id18MouseClicked
       reso(id18);
    }//GEN-LAST:event_id18MouseClicked

    private void buttonAllPlusOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllPlusOneActionPerformed
        reso(id1);
        reso(id2);
        reso(id3);
        reso(id4);
        reso(id5);
        reso(id6);
        reso(id7);
        reso(id8);
        reso(id9);
        reso(id10);
        reso(id11);
        reso(id12);
        reso(id13);
        reso(id14);
        reso(id15);
        reso(id16);
        reso(id17);
        reso(id18);
    }//GEN-LAST:event_buttonAllPlusOneActionPerformed

    private void buttonResoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResoRefreshActionPerformed
        resoRefresh();
    }//GEN-LAST:event_buttonResoRefreshActionPerformed
static void reso(JLabel label){
     int level = 0;
     if(!"".equals(label.getText())){
        level = Integer.valueOf(label.getText()) + 1;
     }else{
         level++;
     }
     int n = 1;
     if(level > 10){
         Object[] options = {MainWindow.messages[71][MainWindow.language], MainWindow.messages[72][MainWindow.language]};
         n = JOptionPane.showOptionDialog(Traviator42.mainWindow,  MainWindow.messages[217][ MainWindow.language],
                                          MainWindow.messages[132][MainWindow.language], JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, 
                                          null, options, options[0]);
     }
     if(n == 1){
        label.setIcon(MainWindow.natiPic[4][2]);
        int num;
        if(label.getName().indexOf(" ") > -1){
            num = Integer.valueOf(label.getName().substring(2, label.getName().indexOf(" ")))-1;
        }else{
            num = Integer.valueOf(label.getName().substring(2))-1;
        }
        int buildingName = MainWindow.resoFields[resoName - 1][num];
        String bName = "";
        if(label.getName().indexOf(" ") == -1){
            switch(buildingName){
            case 0: bName = " woodCutter"; break;
            case 1: bName = " clayPit"; break;
            case 2: bName = " ironMine"; break;
            case 3: bName = " cropField"; break;
            }
        }
        label.setText(String.valueOf(level));
        label.setName(label.getName() + bName);
        MainWindow.addRowToArchitector(label, false, 0);
     }
     }
    
    static void labelNames(){
    id1.setName("id1");    id2.setName("id2");    id3.setName("id3");
    id4.setName("id4");    id5.setName("id5");    id6.setName("id6");
    id7.setName("id7");    id8.setName("id8");    id9.setName("id9");
    id10.setName("id10");    id11.setName("id11");    id12.setName("id12");
    id13.setName("id13");    id14.setName("id14");    id15.setName("id15");
    id16.setName("id16");    id17.setName("id17");    id18.setName("id18");
    
}   
static void resoRefresh(){

try{
    MainWindow.villageChange(MainWindow.comboBoxArcVillages.getSelectedItem().toString(), "dorf1.php", "");
 String MainField = MainWindow.driver.findElement(By.id("village_map")).getAttribute("class").trim();
 resoName = Integer.valueOf(MainField.substring(1));
 MainWindow.labelIco(labelReso, null,  "images/" + MainField + "-ltr.jpg");

    
   String url = MainWindow.driver.getCurrentUrl();
   ArrayList <String> levels = new ArrayList();
   for(int i = 1; i <= 18; i++){
   
     levels.add(MainWindow.driver.findElement
             (By.xpath("//*[@id='village_map']/div[" + i + "]")).getText().trim());
 }
 
 resoFields(levels);
//<editor-fold defaultstate="collapsed" desc="исключения">
}catch(org.openqa.selenium.NoSuchElementException Ex){
    MainWindow.consoleText(Color.RED, MainWindow.messages[4][MainWindow.language]);
    resoRefresh();
}catch(org.openqa.selenium.remote.UnreachableBrowserException Ex){
    MainWindow.consoleText(Color.RED, MainWindow.messages[4][MainWindow.language]);
    resoRefresh();
}catch(org.openqa.selenium.StaleElementReferenceException Ex){
    MainWindow.consoleText(Color.RED, MainWindow.messages[4][MainWindow.language]);
    resoRefresh();
}
//</editor-fold>
}
//<editor-fold defaultstate="collapsed" desc="уровни ресурсов">
static void resoFields(ArrayList <String> levels){
    MainWindow.circleAndLevel(id1, levels.get(0));
    MainWindow.circleAndLevel(id2, levels.get(1));
    MainWindow.circleAndLevel(id3, levels.get(2));
    MainWindow.circleAndLevel(id4, levels.get(3));
    MainWindow.circleAndLevel(id5, levels.get(4));
    MainWindow.circleAndLevel(id6, levels.get(5));
    MainWindow.circleAndLevel(id7, levels.get(6));
    MainWindow.circleAndLevel(id8, levels.get(7));
    MainWindow.circleAndLevel(id9, levels.get(8));
    MainWindow.circleAndLevel(id10, levels.get(9));
    MainWindow.circleAndLevel(id11, levels.get(10));
    MainWindow.circleAndLevel(id12, levels.get(11));
    MainWindow.circleAndLevel(id13, levels.get(12));
    MainWindow.circleAndLevel(id14, levels.get(13));
    MainWindow.circleAndLevel(id15, levels.get(14));
    MainWindow.circleAndLevel(id16, levels.get(15));
    MainWindow.circleAndLevel(id17, levels.get(16));
    MainWindow.circleAndLevel(id18, levels.get(17));
}
//</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAllPlusOne;
    public static javax.swing.JButton buttonResoRefresh;
    public static javax.swing.JLabel id1;
    public static javax.swing.JLabel id10;
    public static javax.swing.JLabel id11;
    public static javax.swing.JLabel id12;
    public static javax.swing.JLabel id13;
    public static javax.swing.JLabel id14;
    public static javax.swing.JLabel id15;
    public static javax.swing.JLabel id16;
    public static javax.swing.JLabel id17;
    public static javax.swing.JLabel id18;
    public static javax.swing.JLabel id2;
    public static javax.swing.JLabel id3;
    public static javax.swing.JLabel id4;
    public static javax.swing.JLabel id5;
    public static javax.swing.JLabel id6;
    public static javax.swing.JLabel id7;
    public static javax.swing.JLabel id8;
    public static javax.swing.JLabel id9;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel7;
    public static javax.swing.JLabel labelReso;
    // End of variables declaration//GEN-END:variables
}
