/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package traviator42.gui.architector;

import traviator42.dto.Village;
import traviator42.gui.common.MainWindow;
import traviator42.gui.common.Traviator42;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Ror
 */
public class Architector2Villy extends javax.swing.JDialog {
String period;
boolean firstTab;
    public Architector2Villy(java.awt.Frame parent, boolean modal, String period, boolean firstTab) {
        super(parent, MainWindow.messages[183][MainWindow.language], modal);
        this.period = period;
        this.firstTab = firstTab;
        
        initComponents();
        jButton1.setText(MainWindow.messages[71][MainWindow.language]);
        jButton2.setText(MainWindow.messages[106][MainWindow.language]);
        
 //<editor-fold defaultstate="collapsed" desc=" Центр экрана ">
 //делаем чтобы приложение появилось в центре экрана
 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
 Dimension frameSize = getSize();
 setLocation(new Point((screenSize.width - frameSize.width) / 2,
 (screenSize.height - frameSize.height) / 2));
///////////////////////////////////////////////////
 //</editor-fold>
       
        jCheckBox1.setText(MainWindow.messages[181][MainWindow.language]);
        jCheckBox2.setText(MainWindow.messages[182][MainWindow.language]);
        jCheckBox3.setText(MainWindow.messages[335][MainWindow.language]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton(MainWindow.natiPic[4][14]);
        jButton2 = new javax.swing.JButton(MainWindow.natiPic[4][24]);

        buttonGroup1.add(jCheckBox1);
        buttonGroup1.add(jCheckBox2);
        buttonGroup1.add(jCheckBox3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox1.setText("jCheckBox1");
        jPanel2.add(jCheckBox1);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox2.setText("jCheckBox2");
        jPanel3.add(jCheckBox2);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox3.setText("jCheckBox3");
        jPanel4.add(jCheckBox3);

        getContentPane().add(jPanel4);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           Village temp;
           
        if(jCheckBox1.isSelected() == true){
           temp = MainWindow.vilList.get(MainWindow.comboBoxArcVillages.getSelectedIndex());
           temp.period = period;
           temp.timeDouble = MainWindow.setTimer(period);
           dispose();
           Traviator42.arch3Reso = new Architector3Reso(Traviator42.mainWindow, true);
           Traviator42.arch3Reso.setVisible(true);
        }else if(jCheckBox2.isSelected() == true){
           if(MainWindow.tribe == 0){
               temp = MainWindow.vilList.get(MainWindow.comboBoxArcVillagesDouble.getSelectedIndex());
               temp.periodDouble = period;
               temp.timeDouble = "00:00:05";
               MainWindow.textFieldArchTime.setText(temp.timeDouble);
           }else{
               temp = MainWindow.vilList.get(MainWindow.comboBoxArcVillages.getSelectedIndex());
               temp.period = period;
               temp.time = "00:00:05";
               MainWindow.textFieldArchTime2.setText(temp.time);
           }
           dispose();
           Traviator42.arch3Villy = new Architector3Villy(Traviator42.mainWindow, true);
           Traviator42.arch3Villy.setVisible(true); 
        }else if(jCheckBox3.isSelected() == true){
           dispose();
           if(firstTab == true)
               temp = MainWindow.vilList.get(MainWindow.comboBoxArcVillages.getSelectedIndex());
           else
               temp = MainWindow.vilList.get(MainWindow.comboBoxArcVillagesDouble.getSelectedIndex());
           temp.buildList.add("auto");
           temp.idList.add(99);
           temp.time = "00:00:05";
           temp.period = period;
           MainWindow.textFieldArchTime.setText(temp.time);
           MainWindow.architectorModel.addRow(new Object[]{"id99 auto"});
           if(MainWindow.tribe == 0){
               temp.buildListD.add("auto");
               temp.idListD.add(99);
               temp.timeDouble = "00:00:09";
               temp.periodDouble = period;
               MainWindow.textFieldArchTime2.setText(temp.timeDouble);
               MainWindow.architectorModelDouble.addRow(new Object[]{"id99 auto"});
           }
        }else{
            jCheckBox1.doClick();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
