/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package traviator42.gui.sergeant;

import traviator42.gui.common.MainWindow;
import traviator42.gui.common.Traviator42;

import java.awt.*;

/**
 *
 * @author Ror
 */
public class SergeantFighterSelection extends javax.swing.JDialog {
int unit = 8;
boolean checkBoxNormalLarge;
    /**
     * Creates new form fighterSeletion
     */
    public SergeantFighterSelection(java.awt.Frame parent, boolean modal) {
        super(parent, MainWindow.messages[161][MainWindow.language], modal);
        initComponents();
        label.setText(MainWindow.messages[160][MainWindow.language]);
        jButton1.setText(MainWindow.messages[71][MainWindow.language]);
        jButton2.setText(MainWindow.messages[106][MainWindow.language]);
         IconCreater();
        //<editor-fold defaultstate="collapsed" desc=" Центр экрана ">
 //делаем чтобы приложение появилось в центре экрана
 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
 Dimension frameSize = getSize();
 setLocation(new Point((screenSize.width - frameSize.width) / 2,
 (screenSize.height - frameSize.height) / 2));
///////////////////////////////////////////////////
 //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton(MainWindow.natiPic[4][14]);
        jButton2 = new javax.swing.JButton(MainWindow.natiPic[4][24]);
        label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chekBoxt1 = new javax.swing.JCheckBox();
        fighter1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        checkBoxT2 = new javax.swing.JCheckBox();
        fighter2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        chekBoxT3 = new javax.swing.JCheckBox();
        fighter3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        chekBoxT5 = new javax.swing.JCheckBox();
        fighter5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        checkBoxT8 = new javax.swing.JCheckBox();
        fighter8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        checkBoxT4 = new javax.swing.JCheckBox();
        fighter4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        checkBoxT6 = new javax.swing.JCheckBox();
        fighter6 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        checkBoxT7 = new javax.swing.JCheckBox();
        fighter7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        buttonGroup1.add(chekBoxt1);
        buttonGroup1.add(checkBoxT2);
        buttonGroup1.add(chekBoxT3);
        buttonGroup1.add(checkBoxT4);
        buttonGroup1.add(chekBoxT5);
        buttonGroup1.add(checkBoxT6);
        buttonGroup1.add(checkBoxT7);
        buttonGroup1.add(checkBoxT8);

        buttonGroup2.add(jCheckBox1);
        buttonGroup2.add(jCheckBox2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label.setText("jLabel1");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        chekBoxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekBoxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(chekBoxt1);
        jPanel1.add(fighter1);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        checkBoxT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxT2ActionPerformed(evt);
            }
        });
        jPanel4.add(checkBoxT2);
        jPanel4.add(fighter2);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        chekBoxT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekBoxT3ActionPerformed(evt);
            }
        });
        jPanel8.add(chekBoxT3);
        jPanel8.add(fighter3);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        chekBoxT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekBoxT5ActionPerformed(evt);
            }
        });
        jPanel11.add(chekBoxT5);
        jPanel11.add(fighter5);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        checkBoxT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxT8ActionPerformed(evt);
            }
        });
        jPanel12.add(checkBoxT8);
        jPanel12.add(fighter8);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        checkBoxT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxT4ActionPerformed(evt);
            }
        });
        jPanel13.add(checkBoxT4);
        jPanel13.add(fighter4);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        checkBoxT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxT6ActionPerformed(evt);
            }
        });
        jPanel14.add(checkBoxT6);
        jPanel14.add(fighter6);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 3, 3));

        checkBoxT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxT7ActionPerformed(evt);
            }
        });
        jPanel15.add(checkBoxT7);
        jPanel15.add(fighter7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(chekBoxt1.isSelected()){unit = 0;}
        if(checkBoxT2.isSelected()){unit = 1;}
        if(chekBoxT3.isSelected()){unit = 2;}
        if(checkBoxT4.isSelected()){unit = 3;}
        if(chekBoxT5.isSelected()){unit = 4;}
        if(checkBoxT6.isSelected()){unit = 5;}
        if(checkBoxT7.isSelected()){unit = 6;}
        if(checkBoxT8.isSelected()){unit = 7;}
        
        if(unit != 8){
//            если выбрана не катапульта и не таран, то ставим идентификатор здания для обучения
            if(jCheckBox1.isSelected() == true && checkBoxT7.isSelected() == false || 
               jCheckBox1.isSelected() == true && checkBoxT8.isSelected() == false){
                  MainWindow.futureRow[1] = MainWindow.units[MainWindow.tribe][unit][MainWindow.language] + " (N)";
            }else{MainWindow.futureRow[1] = MainWindow.units[MainWindow.tribe][unit][MainWindow.language] + " (L)";}
           
        Traviator42.fProperties = new SergeantFighterProperties(Traviator42.mainWindow, true);
        Traviator42.fProperties.setVisible(true);
        dispose();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chekBoxT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekBoxT5ActionPerformed
//   паллыч
     stables();
    }//GEN-LAST:event_chekBoxT5ActionPerformed

    private void checkBoxT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxT6ActionPerformed
//     тевтон
     stables();
    }//GEN-LAST:event_checkBoxT6ActionPerformed

    private void chekBoxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekBoxt1ActionPerformed
//     дубинка
    barrack(); 
    }//GEN-LAST:event_chekBoxt1ActionPerformed

    private void checkBoxT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxT2ActionPerformed
//    копье
     barrack();
    }//GEN-LAST:event_checkBoxT2ActionPerformed

    private void chekBoxT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekBoxT3ActionPerformed
     switch(MainWindow.tribe){
         case 0: barrack(); break;
         case 1: barrack(); break;
         case 2: stables(); break;
     }
    }//GEN-LAST:event_chekBoxT3ActionPerformed

    private void checkBoxT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxT4ActionPerformed
       switch(MainWindow.tribe){
         case 0: stables(); break;
         case 1: barrack(); break;
         case 2: stables(); break;
     }  
    }//GEN-LAST:event_checkBoxT4ActionPerformed

    private void checkBoxT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxT7ActionPerformed
     workShop();
    }//GEN-LAST:event_checkBoxT7ActionPerformed

    private void checkBoxT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxT8ActionPerformed
     workShop();
    }//GEN-LAST:event_checkBoxT8ActionPerformed
  public static void IconCreater(){
        fighter1.setIcon(MainWindow.natiPic[MainWindow.tribe][0]);
        fighter2.setIcon(MainWindow.natiPic[MainWindow.tribe][1]);
        fighter3.setIcon(MainWindow.natiPic[MainWindow.tribe][2]);
        fighter4.setIcon(MainWindow.natiPic[MainWindow.tribe][3]);
        fighter5.setIcon(MainWindow.natiPic[MainWindow.tribe][4]);
        fighter6.setIcon(MainWindow.natiPic[MainWindow.tribe][5]);
        fighter7.setIcon(MainWindow.natiPic[MainWindow.tribe][6]);
        fighter8.setIcon(MainWindow.natiPic[MainWindow.tribe][7]);
       }
  
  void barrack(){
     jCheckBox1.setEnabled(true);
     jCheckBox2.setEnabled(true);
     jCheckBox2.setVisible(true);
     jCheckBox1.setText(MainWindow.messages[165][MainWindow.language]);
     jCheckBox2.setText(MainWindow.messages[168][MainWindow.language]);
     jCheckBox1.doClick();
  }
  void stables(){
     jCheckBox1.setEnabled(true);
     jCheckBox2.setEnabled(true);
     jCheckBox2.setVisible(true);
     jCheckBox1.setText(MainWindow.messages[166][MainWindow.language]);
     jCheckBox2.setText(MainWindow.messages[169][MainWindow.language]);
     jCheckBox1.doClick();
  }
  void workShop(){
     jCheckBox1.setEnabled(true);
     jCheckBox2.setEnabled(false);
     jCheckBox2.setVisible(false);
     jCheckBox1.setText(MainWindow.messages[167][MainWindow.language]);
     jCheckBox2.setText("");
     jCheckBox1.doClick();
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JCheckBox checkBoxT2;
    public static javax.swing.JCheckBox checkBoxT4;
    public static javax.swing.JCheckBox checkBoxT6;
    public static javax.swing.JCheckBox checkBoxT7;
    public static javax.swing.JCheckBox checkBoxT8;
    public static javax.swing.JCheckBox chekBoxT3;
    public static javax.swing.JCheckBox chekBoxT5;
    public static javax.swing.JCheckBox chekBoxt1;
    public static javax.swing.JLabel fighter1;
    public static javax.swing.JLabel fighter2;
    public static javax.swing.JLabel fighter3;
    public static javax.swing.JLabel fighter4;
    public static javax.swing.JLabel fighter5;
    public static javax.swing.JLabel fighter6;
    public static javax.swing.JLabel fighter7;
    public static javax.swing.JLabel fighter8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
